/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.app;

import com.display.CurrentConditionDisplay;
import com.display.ForecastDisplay;
import com.display.StatisticsDisplay;
import com.subject.WeatherData;

public class WeatherStationApp {

	public static void main(String[] args) {
		WeatherData weatherData = new WeatherData();

		CurrentConditionDisplay currentConditionDisplay = new CurrentConditionDisplay(weatherData);
		StatisticsDisplay statisticsDisplay = new StatisticsDisplay(weatherData);
		ForecastDisplay forecastDisplay = new ForecastDisplay(weatherData);
		weatherData.setMeasurements(80, 65, 30.4f);
		weatherData.setMeasurements(82, 70, 29.2f);
		weatherData.setMeasurements(78, 90, 29.2f);
	}
}
